# Rename this file to secrets.toml and fill in your actual values
# Keep this file secret and never commit it to version control

# OpenAI API Key
OPENAI_API_KEY = "your_openai_api_key_here"

# Chroma DB settings
CHROMA_PERSIST_DIRECTORY = "./chroma_db"

# NHS Theme Colors
NHS_THEME_PRIMARY = "#005EB8"
NHS_THEME_SECONDARY = "#41B6E6"
